Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-06, with the labels that each got.

#163 ci: remove `timeout-mutes` from `semantic-pull-request` workflow
  .github/workflows/semantic-pull-request.yaml
Labels: ci

#164 revert: revert #155
  perception_eval/perception_eval/common/dataset_utils.py
  perception_eval/perception_eval/common/schema.py
Labels: revert

#165 chore: release v1.2.2
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#152 feat: update matching policy
  docs/en/perception/metrics.md
  docs/fig/perception/object_matching1.svg
  docs/ja/perception/metrics.md
  perception_eval/perception_eval/evaluation/matching/object_matching.py
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
  perception_eval/perception_eval/evaluation/result/object_result.py
  perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
  perception_eval/perception_eval/tool/perception_analyzer2d.py
  perception_eval/perception_eval/tool/perception_analyzer3d.py
  perception_eval/perception_eval/tool/perception_analyzer_base.py
  perception_eval/test/evaluation/matching/test_objects_filter.py
  perception_eval/test/evaluation/metrics/tracking/test_clear.py
  perception_eval/test/evaluation/metrics/tracking/test_tracking_metrics_score.py
  perception_eval/test/evaluation/result/test_object_result.py
Labels: enhancement

#124 fix(perception): plane distance calculation
  perception_eval/perception_eval/common/point.py
  perception_eval/perception_eval/evaluation/matching/object_matching.py
  perception_eval/test/evaluation/matching/object_matching/test_plane_distance_matching.py
  perception_eval/test/evaluation/metrics/detection/test_ap.py
  perception_eval/test/evaluation/metrics/detection/test_map.py
Labels: bug

#153 feat: add support of exporting confusion matrix for 3D analyzer
  docs/en/perception/analyzer.md
  docs/ja/perception/analyzer.md
  perception_eval/perception_eval/tool/perception_analyzer2d.py
  perception_eval/perception_eval/tool/perception_analyzer3d.py
  perception_eval/perception_eval/tool/perception_analyzer_base.py
  perception_eval/test/perception_lsim.py
  perception_eval/test/perception_lsim2d.py
Labels: enhancement

#167 fix: use mean threshold value for unknwon labeled estimations if unkn…
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
Labels: bug

#169 refactor: not to compare types by `type(...) == type(...)`
  perception_eval/perception_eval/common/geometry.py
  perception_eval/perception_eval/evaluation/matching/object_matching.py
Labels: refactor

#170 fix(perception): resolve analyzer errors
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#171 chore: release v1.2.4
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#161 fix: apply `TransformsDict` while generating object results
  perception_eval/perception_eval/evaluation/matching/object_matching.py
  perception_eval/perception_eval/evaluation/result/object_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
Labels: bug

#172 fix: update to specify transforms
  perception_eval/perception_eval/evaluation/result/object_result.py
Labels: bug

#166 feat: add support of matching any labels
  perception_eval/perception_eval/common/label.py
  perception_eval/perception_eval/config/perception_evaluation_config.py
  perception_eval/perception_eval/config/sensing_evaluation_config.py
  perception_eval/perception_eval/evaluation/matching/__init__.py
  perception_eval/perception_eval/evaluation/matching/object_matching.py
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
  perception_eval/perception_eval/evaluation/result/object_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
  perception_eval/test/config/test_perception_evaluation_config.py
  perception_eval/test/evaluation/matching/test_objects_filter.py
  perception_eval/test/evaluation/result/test_object_result.py
Labels: enhancement

#173 fix: resolve errors depending on analyzer
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#174 fix: avoid calculate error if classification task
  perception_eval/perception_eval/tool/perception_analyzer2d.py
Labels: bug

#175 chore: release v1.2.5
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#178 fix: initialize attributes when that does not exist
  perception_eval/perception_eval/tool/perception_analyzer2d.py
Labels: bug

#177 feat: add velocity norm
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: enhancement
