Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-10, with the labels that each got.

#190 feat(DynamicObjects): add covariance parameter within dynamic objects
  perception_eval/perception_eval/common/object.py
Labels: enhancement

#189 feat(perception): add option on TLR in order to perform whether uuid check first or not.
  perception_eval/perception_eval/config/perception_evaluation_config.py
  perception_eval/perception_eval/evaluation/result/object_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
Labels: enhancement

#191 chore: release v1.2.9
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#193 chore(deps): add support of python3.12
  .github/workflows/build-and-test.yaml
  pyproject.toml
Labels: dependencies, ci

#196 chore: release v1.2.10
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore
