Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-12, with the labels that each got.

#199 fix: skip loading radar pointcloud
  perception_eval/perception_eval/common/dataset_utils.py
Labels: bug

#200 feat(perception): enable to filter based on `region`
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
  perception_eval/perception_eval/tool/utils.py
Labels: enhancement

#201 chore: bump to v1.2.11
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore
