Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-07, with the labels that each got.

#179 feat: integrate critical objects
  perception_eval/perception_eval/evaluation/result/perception_frame_result.py
  perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
  perception_eval/perception_eval/tool/utils.py
  perception_eval/test/perception_lsim.py
  perception_eval/test/perception_lsim2d.py
Labels: enhancement

#180 chore: delete ros_critical_ground_truth_objects
  README.md
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
  perception_eval/test/perception_fp_validation_lsim.py
  perception_eval/test/perception_lsim.py
  perception_eval/test/perception_lsim2d.py
Labels: bug, documentation

#181 chore: release v1.2.6
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#182 fix: max and min distance filter initialization
  perception_eval/perception_eval/config/perception_evaluation_config.py
Labels: bug

#183 feat: add support of `CAM_FRONT_LOWER` in frame id
  perception_eval/perception_eval/common/schema.py
Labels: enhancement

#184 chore: release v1.2.7
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore
