Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-04, with the labels that each got.

#126 feat(perception): update analyzer
  perception_eval/perception_eval/tool/perception_analyzer2d.py
  perception_eval/perception_eval/tool/perception_analyzer3d.py
  perception_eval/perception_eval/tool/perception_analyzer_base.py
  perception_eval/perception_eval/tool/utils.py
Labels: enhancement

#128 fix: fix to set start scene index as 0
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#129 refactor: remove useless for loop
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: refactor

#127 docs: add plot examples for perception field analysis
  docs/en/perception/field_analyzer.md
  docs/fig/perception/plot_field_XY_ratio_tp.png
  docs/fig/perception/plot_field_dist_delta-error_numb_log.png
  docs/ja/perception/field_analyzer.md
Labels: documentation, chore

#130 fix: avoid error if item instance is str
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#131 fix: avoid error if item is str in `get_ground_truth` and `get_estimation`
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#132 chore: release v1.1.8
  perception_eval/package.xml
  pyproject.toml
Labels: dependencies, chore

#134 fix(analyzer): remove statements causing exception
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#136 feat: update error analisys
  perception_eval/perception_eval/tool/perception_analyzer2d.py
  perception_eval/perception_eval/tool/perception_analyzer3d.py
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: enhancement

#138 fix: analyzer/unstable analysis
  perception_eval/perception_eval/tool/perception_analyzer2d.py
  perception_eval/perception_eval/tool/perception_analyzer3d.py
  perception_eval/perception_eval/tool/perception_analyzer_base.py
Labels: bug

#139 fix: return None if there is no objects in the specified distance range
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: bug

#140 chore: release v1.1.9
  perception_eval/package.xml
  pyproject.toml
Labels: dependencies, chore

#142 fix: resolve coordinates transformation depending on frame id of an o…
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: bug

#143 fix: transform NN points from map to base link
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: bug

#144 fix: disable to plot nn point state
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: bug

#145 chore: release v1.1.10
  perception_eval/package.xml
  pyproject.toml
Labels: dependencies, chore

#146 ci: update workflow cache
  .cspell.json
  .github/actions/install/action.yaml
  .github/workflows/build-and-test-mock.yaml
  .github/workflows/build-and-test.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/semantic-pull-request.yaml
  .github/workflows/spell-check.yaml
Labels: ci

#147 ci: add workflow timeout
  .cspell.json
  .github/workflows/build-and-test.yaml
  .github/workflows/cancel-privious-workflows.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/semantic-pull-request.yaml
  .github/workflows/spell-check.yaml
Labels: ci
