Repository tier4/autoware_perception_evaluation, pull requests merged in 2024-02, with the labels that each got.

#120 feat: add gt frame interpolation function
  perception_eval/perception_eval/common/dataset.py
  perception_eval/perception_eval/common/geometry.py
  perception_eval/perception_eval/manager/_evaluation_manager_base.py
  perception_eval/test/common/test_geometry.py
Labels: enhancement

#121 chore: update version to v1.1.6
  perception_eval/package.xml
  pyproject.toml
Labels: dependencies, chore

#122 feat: add `stroller` and `motorcycle`
  docs/en/perception/label.md
  docs/ja/perception/label.md
  perception_eval/perception_eval/common/label.py
Labels: documentation, enhancement

#123 chore: update version to v1.1.7
  perception_eval/package.xml
  pyproject.toml
Labels: dependencies, chore
