Repository tier4/autoware_perception_evaluation, pull requests merged in 2025-04, with the labels that each got.

#11 feat(prediction): add support of prediction evaluation
  perception_eval/perception_eval/common/dataset.py
  perception_eval/perception_eval/common/dataset_utils.py
  perception_eval/perception_eval/common/object.py
  perception_eval/perception_eval/common/state.py
  perception_eval/perception_eval/config/_evaluation_config_base.py
  perception_eval/perception_eval/config/perception_evaluation_config.py
  perception_eval/perception_eval/config/sensing_evaluation_config.py
  perception_eval/perception_eval/evaluation/metrics/config/prediction_metrics_config.py
  perception_eval/perception_eval/evaluation/metrics/metrics.py
  perception_eval/perception_eval/evaluation/metrics/metrics_score_config.py
  perception_eval/perception_eval/evaluation/metrics/prediction/__init__.py
  perception_eval/perception_eval/evaluation/metrics/prediction/path_displacement_error.py
  perception_eval/perception_eval/evaluation/metrics/prediction/prediction_metrics_score.py
  perception_eval/perception_eval/evaluation/metrics/prediction/utils.py
  perception_eval/perception_eval/evaluation/metrics/tracking/tracking_metrics_score.py
  perception_eval/perception_eval/evaluation/result/perception_frame_result.py
  perception_eval/perception_eval/manager/perception_evaluation_manager.py
  perception_eval/perception_eval/util/debug.py
  perception_eval/test/perception_lsim.py
Labels: enhancement, prediction

#207 fix(perception): re-setting `__hash__` to use `__eq__`
  perception_eval/perception_eval/common/evaluation_task.py
  perception_eval/perception_eval/common/label.py
  perception_eval/perception_eval/common/schema.py
  perception_eval/perception_eval/common/shape.py
  perception_eval/perception_eval/common/status.py
  perception_eval/perception_eval/tool/utils.py
Labels: bug

#211 feat(perception): add new column
  perception_eval/perception_eval/tool/perception_analyzer3d.py
Labels: enhancement

#208 fix(perception): fix plane distance when there is yaw difference between gt and est
  perception_eval/perception_eval/common/object.py
  perception_eval/perception_eval/evaluation/matching/object_matching.py
Labels: bug

#213 chore: bump to v1.2.12
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore
