Repository tier4/autoware_perception_evaluation, pull requests merged in 2025-06, with the labels that each got.

#216 fix(perception): fix plane distance about bbox dimension when there is yaw difference between gt and est
  perception_eval/perception_eval/evaluation/matching/object_matching.py
Labels: bug

#219 chore(deps): use uv instead of poetry
  .github/actions/install/action.yaml
  .github/workflows/build-and-test.yaml
  .gitignore
  .vscode/settings.json
  docs/en/get_started.md
  docs/ja/get_started.md
  perception_eval/perception_eval/util/debug.py
  perception_eval/perception_eval/visualization/eda_tool.py
  perception_eval/test/evaluation/metrics/detection/test_map.py
  perception_eval/test/test_copyright.py
  perception_eval/test/test_flake8.py
  perception_eval/test/test_pep257.py
  pyproject.toml
Labels: documentation, dependencies, ci, chore

#218 feat: add timestamp list of predicted path
  perception_eval/perception_eval/common/dataset_utils.py
  perception_eval/perception_eval/common/object.py
  perception_eval/perception_eval/common/state.py
  perception_eval/perception_eval/util/debug.py
  perception_eval/test/util/dummy_object.py
Labels: enhancement

#223 feat(perception): fix typo and add cspell
  .cspell.json
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
Labels: enhancement
