Repository tier4/autoware_perception_evaluation, pull requests merged in 2025-07, with the labels that each got.

#229 fix: compute matchable threshold from estimation label if gt label is FP
  perception_eval/perception_eval/common/threshold.py
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
  perception_eval/perception_eval/evaluation/metrics/detection/ap.py
  perception_eval/perception_eval/evaluation/metrics/tracking/clear.py
  perception_eval/perception_eval/evaluation/result/object_result.py
Labels: bug

#228 fix(perception): fix how to count FP and TN in fp_validation and add method to get number of GT
  perception_eval/perception_eval/evaluation/matching/objects_filter.py
  perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
Labels: bug

#231 chore: bump to v1.2.15
  perception_eval/package.xml
  pyproject.toml
  setup.cfg
Labels: dependencies, chore

#235 feat(perception): add pass_fail_result for pickle
  perception_eval/perception_eval/evaluation/result/perception_frame_result.py
Labels: enhancement
